### ISSUE TITLE
Possibility of allowing the serving of static files?

### ISSUE THREAD

**Issue by NigelGreenway** [mbarquin/reactphp-slim#2]
I have a scenario whereby I want to Dockerize micro apps and am unable to use Nginx as I will need to either:

 1 spin up 2 docker containers 1:Nginx & 1:PHP-FPM
 2 spin up 1 docker container with Nginx+PHP-FPM

The 1st option won't work for me as the possibility of having 100 micro apps means I need 200 docker containers running which will be resource heavy on the server.

The 2nd option is a no no as it is bad practise in the world of docker to have 1 container running 2+ processes inside it.

I then come across ReactPHP, and then I found this repository. So I have tried it out and works really well... until you want to serve static content?

So, I have tried an initial implementation of allowing ReactPHP to server static content. Please see the following [gist](https://gist.github.com/NigelGreenway/a2e8f0e55e51e8fe3c773b5d27d96da9) with the quick example of my implementation.

The clean way I can think of currently is by allowing something like Ngnix to fetch content from a CDN of some sort but then I'm wondering if this could also be a solution?

I would love to here if/how you have solved this problem and feedback on the idea above as I can submit a PR if required?

**Comment by mbarquin** [comment]
HI,

Excuse me, I have been a bit busy these days, I'm reading now your gist. I
think serving static content would be a great improvement. I've never
thought about it, the main intention for the server was to serve a REST
API, and after that I was curious about file uploading... The code seems
good, if you want plese make a pull request, After that I will try to
refactor a bit the code. I should have done it before, but with your
improvement it will be a good time for it.

Thanks in advance.
kind regards,

Moi

2017-04-21 2:47 GMT+02:00 Nigel Greenway <notifications@github.com>:

**Comment by mbarquin** [comment]
HI again,

About the assets... I always think about this server as a pure API server,
if you want to serve assets,
    I'm not sure, but the CDN solution will free a bit your server.
    If you serve them you will have a bit more control on them.

    In one of my APIs I had sent images as base64 encoded, but under a
framework route to control user acces rights

I think this code will allow users to do what they want...

:)


2017-04-21 2:47 GMT+02:00 Nigel Greenway <notifications@github.com>:

**Comment by NigelGreenway** [comment]
@mbarquin So, I have created a PR[#3] in regards to the changes I put forward but I have also added an extra piece of logic which I am thinking would negate the issue of people wanting to just use the ReactPHP / SlimPHP wrapper for an API only _*OR*_ for a full content features web server.

Please [see here](https://github.com/mbarquin/reactphp-slim/pull/3/files#diff-c611f5024b5b13f69f779505d1c6735eR190) for the change. It will check if `Server#webRoot` is `null` and then either serve an API only server or a full webserver with asset serving.

Thoughts?

**Comment by NigelGreenway** [comment]
okay, as I wrote ^^, I thought it might be better to have two separate methods:

`Server#runApiServer` and `Server#runWebServer` as it is more explicit and allows for the methods to handle the correct implementation without the need to add a further if statement?

**Comment by NigelGreenway** [comment]
I have updated #3 with the new explicit methods for server type.

**Comment by NigelGreenway** [comment]
Closing this as this is to be discussed further as an RFC
